### ISSUE TITLE
Time Zones

### ISSUE THREAD

**Issue by codebytere** [josh-/TodayFlights#2]
it doesn't appear that the app keeps track of timezones; this flight: 

<img width="326" alt="screen shot 2018-01-06 at 6 09 56 pm" src="https://user-images.githubusercontent.com/2036040/34645846-d463aff2-f30c-11e7-86f3-484d5d5ded2a.png">

says arrived even though it arrives at 5:48am **in paris** and not local time, and the date appears to be off as well since this flight both took off and landed on **1/7/18**. I can try to take a crack at fixing this, if that would be helpful!

**Comment by josh-** [comment]
Hi @codebytere, thanks for raising this issue! 🙌 

Unfortunately, due to the way TodayFlights is implemented (using the `FlightUtilities` private Apple framework - more info available in a talk I gave [here](https://www.youtube.com/watch?v=OeASRYMT3WA)) there is limited ability to modify what data is retrieved or what the UI presents, as far as I've been able to find. The notification centre widget is essentially a wrapper around the `FUFlightViewController` class, [whose header file is included here](https://github.com/josh-/TodayFlights/blob/master/TodayFlights/PrivateHeaders/FlightUtilities/FUFlightViewController.h).

Apple made some substantial changes to the functionality and appearance of the flight view controller in High Sierra, so perhaps the incorrect date issue is resolved in macOS 10.13? For example, this is how the most recent `MEA209` flight looks in the latest macOS:

<img width="333" alt="screen shot 2018-01-20 at 6 39 15 pm" src="https://user-images.githubusercontent.com/712727/35181244-46925b90-fe12-11e7-83b2-68f28df79adc.png">

If in the future you notice some more incorrect information, please don't hesitate to let me know so the API can be queried directly (unfortunately only flights from the last 7 days can be viewed, so I'm too late to look at what the API was returning for the 7th of Jan – sorry about that! 😞 )
